config/routes.rb
Rails.application.routes.draw do
  get 'orders/bought'
  get 'orders/sold'
  resources :items
  get 'users/show'
  devise_for :users
  root "items#index"

  post "items/:id/order", to: "items#place_order", as: "place_order"

  get "/payments/success", to: "payments#success"
  # post "/payments/webhook", to: "payments#webhook"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/item.rb
class Item < ApplicationRecord
  belongs_to :user
  has_many :orders

  enum category: {Clothes: 0, Toys: 1, Kitchenware: 2, Furniture: 3, Misc: 4}
  has_one_attached :item_image

  # if don't have has_one_attached, will show -- unknown attribute 'image' for Item.

  validates :title, presence: true
  validates :price, numericality: { greater_than: 0 }

  def dollar_price
    price / 100.0
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :item
  belongs_to :buyer, foreign_key: "buyer_id", class_name: "User"
  belongs_to :seller, foreign_key: "seller_id", class_name: "User"
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates_presence_of :email
  validates_presence_of :first_name
  validates_presence_of :last_name
  validates_presence_of :encrypted_password
  validates_confirmation_of :encrypted_password
  validates_length_of :encrypted_password, minimum: 6

  has_many :items

  has_many :sold_orders, foreign_key: "seller_id", class_name: "Order"
  has_many :bought_orders, foreign_key: "buyer_id", class_name: "Order"
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  before_action :update_allowed_parameters, if: :devise_controller?

  protected

  def update_allowed_parameters
    devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:first_name, :last_name, :email, :password, :address, :post_code)}
    devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:first_name, :last_name, :email, :password, :current_password, :address, :post_code)}
  end

end

app/controllers/items_controller.rb
include MailgunHelper

class ItemsController < ApplicationController
  before_action :set_item, only: %i[ show edit update destroy]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :authorize_user, only: [:edit, :update, :destroy]



  # GET /items or /items.json
  def index
    if params.has_key?(:category)
      category = params[:category]
      # for filter the item by category, select all the items that match the selected category_id in item table in sql database
      @items = Item.find_by_sql("SELECT * FROM Items WHERE category=#{category}")
      # hide the search-bar when perform category search
      @show_search_bar = false
    elsif params.has_key?(:keyword)
      keyword = params[:keyword]
      # for the search bar function, select all the items that the item title partially match the keyword that the user typed, also it's case insensitive
      @items = Item.find_by_sql("SELECT * FROM Items WHERE title ILIKE '%#{keyword}%'")
      # hide the search-bar when perform category search
      @show_search_bar = false
    else
      @items = Item.all

      @show_search_bar = true
    end
  end

  # GET /items/1 or /items/1.json
  def show
    if current_user
      session = Stripe::Checkout::Session.create(
        payment_method_types: ['card'],
        customer_email: current_user.email,
        line_items: [{
                       name: @item.title,
                       # description: @item.description,
                       images: [rails_blob_url(@item.item_image)],
                       amount: (@item.price * 100).to_i,
                       currency: 'aud',
                       quantity: 1,
                     }],
        payment_intent_data: {
          metadata: {
            item_id: @item.id,
            user_id: current_user.id
          }
        },
        success_url: "#{root_url}payments/success?itemId=#{@item.id}",
        cancel_url: "#{root_url}items"
      )
      @session_id = session.id
    end
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items or /items.json
  def create
    @item = Item.new(item_params)
    @item.user = current_user

    respond_to do |format|
      if @item.save
        format.html { redirect_to users_show_path, notice: "Item was successfully created." }
        format.json { render :show, status: :created, location: @item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /items/1 or /items/1.json
  def update
    respond_to do |format|
      if @item.update(item_params)
        format.html { redirect_to users_show_path, notice: "Item was successfully updated." }
        format.json { render :show, status: :ok, location: @item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /items/1 or /items/1.json
  def destroy
    @item.destroy

    respond_to do |format|
      format.html { redirect_to users_show_path, notice: "Item was successfully deleted." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    def authorize_user
      if current_user.id != @item.user_id
        flash[:alert] = "you cannot do that!"
        redirect_to items_path
      end
    end

    # Only allow a list of trusted parameters through.
    def item_params
      params.require(:item).permit(:title, :category, :price, :item_image, :sold, :user_id)
    end
end

app/controllers/items_unused_controller.rb
class ItemsUnusedController < ApplicationController
  def home
  end

  def restricted
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  def bought
    @bought_items = current_user.bought_orders
  end

  def sold
    @sold_items = current_user.sold_orders
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController

  def success
    @item = Item.find(params["itemId"])

    Order.create(
      item_id: @item.id,
      seller_id: @item.user_id,
      buyer_id: current_user.id
    )

    @item.update(sold: true)

    seller_email = User.find_by_id(@item.user_id).email
    buyer_email = current_user.email
    buyer_name = current_user.first_name
    item_title = @item.title

    # Put the mailout inside the exception, so when it failed the website still function
    begin
      MailgunHelper::send_email('admin@garagesale.com', seller_email,'Your item is sold', " #{buyer_name} bought one of your item #{item_title}.")
      MailgunHelper::send_email('admin@garagesale.com', buyer_email,'You bought an item', "You bought an item #{item_title}." )
    rescue => e
    end

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show

  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/items_helper.rb
module ItemsHelper
  class MyWorker
    include Rails.application.routes.url_helpers

    def my_url
      polymorphic_url(@item.item_image).variant(resize: "300x300")
    end
  end
end

app/helpers/items_unused_helper.rb
module ItemsUnusedHelper
end

app/helpers/mailgun_helper.rb
# require 'mailgun-ruby'

# module MailgunHelper

# def send_email(from, to, subject, text)
#   api_key = Rails.application.credentials.mailgun[:api_key]
#   domain = Rails.application.credentials.mailgun[:domain]
#   mg_client = Mailgun::Client.new(api_key)

#   message_params =  {
#     from: from,
#     to:   to,
#     subject: subject,
#     text:    text
#   }

#   mg_client.send_message(domain, message_params).to_h!
# end

# end

app/helpers/orders_helper.rb
module OrdersHelper

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/items/_card.html.erb
  <div class="card">
    <% if item.item_image.attached? %>
      <%= image_tag item.item_image, alt: "#{item.title} image", class: "card-img-top card-img" %>
    <% else %>
      <%= image_tag "Dog.jpeg", alt: default_formats, class: "card-img-top card-img" %>
    <% end %>
    <div class="card-body">
      <h5 class="card-title"><%= item.title %></h5>
      <p class="card-text">Price:  <%= number_to_currency(item.price.to_i) %></p>
      <%= link_to "Show More", item_path(item.id), class: "btn btn-primary btn-right" %>
    </div>
  </div>

app/views/items/_form.html.erb
<%= simple_form_for(@item) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :price %>
    <%= f.input :category, collection: ["Clothes", "Toys", "Kitchenware", "Furniture", "Misc"] %>
    <br>
    <%= f.file_field :item_image, accept: 'image/png, image/jpg, image/jpeg'%>
  </div>
  <br>
  <div class="form-actions btn btn-info">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<% if @show_search_bar %>
<div class="search-container">
  <div class="search-section">
    <div class="form-group has-search">
      <span class="fa fa-search form-control-feedback"></span>
      <input type="text" name="search_text" class="form-control" placeholder="Search anything you want to buy then press [Enter]">
      <a class="link" href="/?keyword"></a>
    </div>
  </div>
</div>
  <% end %>

<!--search function detect keyword then use Enter to trigger by using JavaScript -->
<script type="text/javascript" data-template="console" nonce="">
    var input = document.querySelector("input[name=\"search_text\"]");
    input.addEventListener("keyup", (event) => {
        if (event.key === "Enter") {
            window.location.href = '/?keyword=' + input.value
        }
    });
</script>

<br>
<div class="list-title">
  <h5>Good Choice!</h5>
  <h5>Our website reviews with an average of 4.8 out of 5 stars <%= (image_tag 'star2.png', size: '32x32')*5 %></h5>
<!--  <i class="fa-solid fa-star"></i>-->

</div>

<div class="row">
  <% @items.each do |item| %>
    <div class="col-md-3">
      <%= render 'card', item: item %>
    </div>
  <% end %>
</div>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>

<div class="show-item-container">
  <div class="non-map-section">
    <div class="show-item-image">
      <% if @item.item_image.attached? %>
        <%= image_tag @item.item_image, alt: @item.title %>
      <% else %>
        <%= image_tag "Dog.jpeg", alt: default_formats %>
      <% end %>
    </div>

    <div>
      <% if @item.sold %>
        <h1>SOLD</h1>
      <% elsif current_user && current_user.id == @item.user_id %>
        <h1>It is your own item</h1>
      <% elsif current_user %>
        <button data-stripe="payment">Buy Now! <%= number_to_currency(@item.price.to_i) %></button>

        <script src="https://js.stripe.com/v3/"></script>
        <script>
            document.querySelector("[data-stripe='payment']").addEventListener("click", () => {
                const stripe = Stripe("<%= Rails.application.credentials.dig(:stripe, :public_key) %>");
                stripe.redirectToCheckout ({
                    sessionId: "<%= @session_id %>"
                });
            });
        </script>
      <% else %>
        <h1>Please log in to make a purchase</h1>
      <% end %>
    </div>
    <br>
    <div>
      <p>
        <strong>Title:</strong>
        <%= @item.title %>
      </p>

      <p>
        <strong>Category:</strong>
        <%= @item.category %>
      </p>

      <p>
        <strong>Price:</strong>
        <%= number_to_currency(@item.price.to_i) %>
      </p>
    </div>
 </div>

  <div class="mapouter">
    <div class="gmap_canvas"><iframe width="600" height="500" id="gmap_canvas" src="https://maps.google.com/maps?q=<%= User.find_by_id(@item.user_id).address %>&t=&z=13&ie=UTF8&iwloc=&output=embed" frameborder="0" scrolling="no" marginheight="0" marginwidth="0"></iframe>
      <a href="https://fmovies-online.net"></a>
      <br>
      <style>.mapouter{position:relative;text-align:right;height:500px;width:600px;}</style>
      <a href="https://www.embedgooglemap.net">custom google maps for website</a>
      <style>.gmap_canvas {overflow:hidden;background:none!important;height:500px;width:600px;}</style>
    </div>
  </div>
</div>

<div class="show-item-backbutton">
  <%= link_to 'Back', items_path, class: "btn btn-outline-dark" %>
</div>

app/views/items_unused/home.html.erb
<h1>Items#home</h1>
<p>Find me in app/views/items/home.html.erb</p>

app/views/items_unused/restricted.html.erb
<h1>Items#restricted</h1>
<p>Find me in app/views/items/restricted.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GarageSalesApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <!--  Bootstrap styling -->
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.5/dist/umd/popper.min.js" integrity="sha384-Xe+8cL9oJa6tN/veChSP7q+mnSPaj5Bcu9mPX5F5xIGE0DVittaqT5lorf0EI7Vk" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-kjU+l4N0Yf4ZOJErLsIcvOU2qSb74wXpOhqTvwVx3OElZRweTnQ6d31fXEoRD1Jy" crossorigin="anonymous"></script>

    <!-- Load icon library -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <div class="container">
    <% unless current_page?(users_show_path) || current_page?(orders_sold_path) || current_page?(orders_bought_path) %>
      <%= render 'shared/nav' %>
    <% end %>
    <p class="notice"><%= notice %></p>
    <p class="alert"><%= alert %></p>
    <%= yield %>

    <%# if Rails.env.development? %>
      <%# console %>
    <%# end %>
  </div>
  </body>
</html>

app/views/orders/_nav-admin.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light justify-content-end">
  <div class="container-fluid">
    <a class="navbar-brand" href="/">BACK</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarText" aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <ul class="nav justify-content-end">
      <li class="nav-item">
        <%= link_to "My Profile", users_show_path, class: "nav-link active" %>
      </li>
      <li class="nav-item">
        <%= link_to "Bought", orders_bought_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sold", orders_sold_path, class: "nav-link" %>
      </li>
    </ul>
  </div>
</nav>

app/views/orders/bought.html.erb
<%= render 'orders/nav-admin' %>

<h1>Items you have bought</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Seller</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @bought_items.each do |bought_item| %>
    <tr>
      <td><%= bought_item.item.title %></td>
      <td><%= number_to_currency(bought_item.item.price) %></td>
      <td><%= bought_item.seller.email %></td>
      <td><%= bought_item.item.category %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/orders/sold.html.erb
<%= render 'orders/nav-admin' %>

<h1>Items you have sold</h1>

<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Buyer</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% @sold_items.each do |sold_item| %>
    <tr>
      <td><%= sold_item.item.title %></td>
      <td><%= number_to_currency(sold_item.item.price) %></td>
      <td><%= sold_item.buyer.email %></td>
      <td><%= sold_item.item.category %></td>
    </tr>
  <% end %>
  </tbody>
</table>

app/views/payments/success.html.erb
Thank you for your purchase!
Your order of <%= @item.title %> is on its way!
A confirm email will send to you shortly!
<br>
<br>
<%= link_to "Go To Home", items_path, class: "btn btn-info" %><br>

app/views/shared/_nav.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <%#= image_tag 'sales.png', size: '34x34', class: 'logo' %>
<!--    &nbsp &nbsp-->
    <a class="navbar-brand" href="/">GarageSale Items</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="/?category=0">Clothes</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/?category=1">Toys</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/?category=2">Kitchenware</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/?category=3">Furniture</a>
          </li>

          <li class="nav-item">
            <a class="nav-link" href="/?category=4">Misc</a>
          </li>
        </ul>

      <span class="d-flex">
        <% if user_signed_in? %>
          <%= link_to current_user.email, users_show_path, class: "btn btn-outline-info" %>

        <% else %>
         <%= link_to "Sign up", new_user_registration_path, class: "btn btn-outline-primary" %>
         <%= link_to "Sign in", new_user_session_path, class: 'btn btn-outline-primary' %>
        <% end %>
      </span>
    </div>
  </div>
</nav>

app/views/users/show.html.erb
<%= render 'orders/nav-admin' %>
<br>
<br>
<% if user_signed_in? %>
  <h3> <%= "Welcome to your Profile page, #{current_user.email}" %></h3>
 <br>
  <h2>My Profile:</h2>
  <%= link_to "Update profile", edit_user_registration_path, class: "btn btn-outline-info" %>
  <%= link_to "Sign Out", destroy_user_session_path, method: :delete, class: "btn btn-outline-info" %>
  <br>
  <p><%= "First Name: #{current_user.first_name}" %></p>
  <p><%= "Last name: #{current_user.last_name}" %></p>
  <p><%= "Address: #{current_user.address}" %></p>
  <p><%= "Post code:  #{current_user.post_code}" %></p>
<% end %>
<br>

<h2>Items for sale:</h2>
<%= link_to "Sell New Item", new_item_path, class: "btn btn-outline-info" %>

<br>
<table class="table table-striped">
  <thead>
  <tr>
    <th>Title</th>
    <th>Price</th>
    <th>Sold</th>
    <th>Category</th>
    <th colspan="3"></th>
  </tr>
  </thead>

  <tbody>
  <% current_user.items.each do |item| %>
    <tr>
      <td><%= item.title %></td>
      <td><%= number_to_currency(item.price) %></td>
      <td><%= item.sold %></td>
      <td><%= item.category %></td>
      <td><%= link_to 'Edit', edit_item_path(item) %></td>
      <td><%= link_to 'Delete', item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
  </tbody>
</table>